name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: spnotifierfuncapp  # set this to your application's name
  PUBLISH_DIRECTORY: publish_output
  ARTIFACT_NAME: publish_artifact
  DOTNET_VERSION: 3.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install .NET Core format tool
      run: dotnet tool update -g dotnet-format

    - name: Build project
      run: dotnet build -c Release --output ./${{ env.PUBLISH_DIRECTORY }}

    - name: Test project
      run: dotnet test

    - name: Lint C# code
      run: dotnet format --check --verbosity detailed

    - name: Upload publish output
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.PUBLISH_DIRECTORY }}/*

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download publish output
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
